---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    package-operator.run/phase: ns
  labels:
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
  name: rukpak-system
