---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    package-operator.run/phase: deploy
  name: crd-validation-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-validation-webhook
subjects:
  - kind: ServiceAccount
    name: crd-validation-webhook
    namespace: crdvalidator-system
