---
apiVersion: v1
kind: Service
metadata:
  annotations:
    package-operator.run/phase: deploy
  name: core
  namespace: rukpak-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: core
