---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    package-operator.run/phase: deploy
  name: bundle-reader
rules:
  - nonResourceURLs:
      - /bundles/*
    verbs:
      - get
