apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reference-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reference-addon
subjects:
- kind: ServiceAccount
  name: reference-addon-operator
  namespace: reference-addon-system
