apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: metrics-proxy-tls
  labels:
    app.kubernetes.io/name: reference-addon-operator
  name: reference-addon-metrics
  namespace: reference-addon
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8443
  selector:
    app.kubernetes.io/name: reference-addon-operator
