---
apiVersion: v1
kind: Service
metadata:
  annotations:
    package-operator.run/phase: deploy
  name: helm-provisioner
  namespace: rukpak-system
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: helm-provisioner
