---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    package-operator.run/phase: deploy
  name: crd-validation-webhook-certificate
  namespace: crdvalidator-system
spec:
  dnsNames:
    - crd-validation-webhook.crdvalidator-system.svc
  issuerRef:
    name: selfsigned
  secretName: crd-validation-webhook-certificate
