apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: rukpak
spec:
  config:
    openAPIV3Schema:
      properties:
        rukpakImage:
          description: rukpakImage is the reference to the image containing rukpak.
          type: string
          default: "rukpak:latest"
      required:
        - rukpakImage
      type: object
  scopes:
    - Namespaced
    - Cluster
  phases:
    - name: ns
    - name: deploy
  availabilityProbes:
    - probes:
        - condition:
            type: Available
            status: "True"
        - fieldsEqual:
            fieldA: .status.updatedReplicas
            fieldB: .status.replicas
      selector:
        kind:
          group: apps
          kind: Deployment
    - probes:
        - condition:
            type: Established
            status: "True"
      selector:
        kind:
          group: apiextensions.k8s.io
          kind: CustomResourceDefinition
